spring:
  application:
    name: day1
  profiles:
    active: ${APP_PROFILE:dev}

  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: never

server:
  port: 8080

app:
  jwt:
    issuer: yoedu-demo
    secret: yoedu-demo-secret-key-12345678901234567890
    access-token-ttl-minutes: 480
    refresh-token-ttl-days: 7
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    disable-swagger-default-url: true
    operations-sorter: alpha
    tags-sorter: alpha