package com.yo.day1.service.impl;

import com.yo.day1.common.exception.BadRequestException;
import com.yo.day1.common.exception.NotFoundException;
import com.yo.day1.domain.entity.Course;
import com.yo.day1.domain.entity.CourseClass;
import com.yo.day1.domain.entity.Room;
import com.yo.day1.domain.enums.ClassStatus;
import com.yo.day1.dto.courseclass.CourseClassResponse;
import com.yo.day1.dto.courseclass.CourseClassUpsertRequest;
import com.yo.day1.repository.*;
import com.yo.day1.service.CourseClassService;
import lombok.RequiredArgsConstructor;
import org.modelmapper.ModelMapper;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDate;
import java.util.List;
import java.util.Optional;


@Service
@RequiredArgsConstructor
public class CourseClassServiceImpl implements CourseClassService {

    private final CourseClassRepository courseClassRepository;

    private final ScheduleSlotRepository scheduleSlotRepository;

    private final CourseRepository courseRepository;

    private final TeacherRepository teacherRepository;

    private final RoomRepository roomRepository;

    private final ModelMapper mapper;

    CourseClassResponse toCourseClassResponse(CourseClass cc) {
        return mapper.map(cc, CourseClassResponse.class);
    }

    CourseClass copyToCourseClass(CourseClassUpsertRequest req, CourseClass cc) {
        if (req.getCourseId() != null){
            courseRepository.findById(req.getCourseId()).ifPresent(cc::setCourse);
        }

        if(req.getScheduleSlotId() != null){
            scheduleSlotRepository.findById(req.getScheduleSlotId()).ifPresent(cc::setSlot);
        }

        if(req.getRoomId() != null){
            roomRepository.findById(req.getRoomId()).ifPresent(cc::setRoom);
        }

        if(req.getMainTeacherId() != null){
            teacherRepository.findById(req.getMainTeacherId()).ifPresent(cc::setMainTeacher);
        }

        if(req.getAssistantTeacherId() != null){
            teacherRepository.findById(req.getAssistantTeacherId()).ifPresent(cc::setAssistantTeacher);
        }
        return cc;
    }

    public List<CourseClassResponse> findAll(){
        return courseClassRepository.findAll().stream()
                .map(this::toCourseClassResponse).toList();

    }
    public Optional<CourseClassResponse> findById(Long id) {
        return courseClassRepository.findById(id).map(this::toCourseClassResponse);
    }

    public CourseClassResponse create (CourseClassUpsertRequest req){
        // Lấy thông tin phòng học và khóa học từ database
        Room room = roomRepository.findById(req.getRoomId())
                .orElseThrow(() -> new NotFoundException("Room not found"));

        Course course = courseRepository.findById(req.getCourseId())
                .orElseThrow(() -> new NotFoundException("Course not found"));
        // Kiểm tra sĩ số tối đa
        if (req.getMaxStudents() > room.getCapacity()) {
            throw new BadRequestException(
                    "Sĩ số tối đa của lớp (" + req.getMaxStudents() +
                            ") vượt quá sức chứa của phòng " + room.getName() + " (" + room.getCapacity() + " chỗ)!"
            );
        }
        CourseClass courseClass = mapper.map(req, CourseClass.class);
        courseClass.setRoom(room);
        courseClass.setCourse(course);
        // 3. Tự động sinh classCode theo convention: {courseCode}-{roomName}-{year}
        int currentYear = LocalDate.now().getYear();
        String cleanRoomName = room.getName().replaceAll("\\s+", "");
        String autoGeneratedCode = course.getCourseCode() + "-" + cleanRoomName + "-" + currentYear;

        courseClass.setCodeCode(autoGeneratedCode.toUpperCase());

        CourseClass result = courseClassRepository.save(courseClass);
        return toCourseClassResponse(result);
    }

    public CourseClassResponse update (Long id, CourseClassUpsertRequest req) throws NotFoundException {
        //Hàm update này khá phức tạp
        //
        Optional<CourseClass> courseClass = courseClassRepository.findById(id);
        if(courseClass.isPresent()){
            CourseClass cc = courseClass.get();

            copyToCourseClass(req, cc);

            CourseClass result = courseClassRepository.save(cc);
            return toCourseClassResponse(result);
        } else {
            throw new NotFoundException("Course not found");
        }
    }
    @Override
    public void delete(Long id) throws NotFoundException {

        Optional<CourseClass> courseClass = courseClassRepository.findById(id);

        if(courseClass.isPresent()) {
            courseClassRepository.deleteById(id);
        } else {
            throw new NotFoundException("Course class not found");
        }
    }
    @Override
    public List<CourseClassResponse> search(String keyword) {

        return courseClassRepository
                .findByNameContainingIgnoreCase(keyword)
                .stream()
                .map(this::toCourseClassResponse)
                .toList();
    }
    @Transactional(readOnly = true)
    public CourseClass getCourseClass(Long id) {
        return courseClassRepository.findById(id)
                .orElseThrow(() -> new NotFoundException("Course class not found: " + id));
    }
    @Override
    @Transactional(readOnly = true)
    public List<CourseClassResponse> findByStatus(ClassStatus status) {
        return courseClassRepository.findByStatus(status).stream()
                .map(courseClass -> mapper.map(courseClass, CourseClassResponse.class))
                .toList();
    }

}